[build]
  # Build command for the frontend
  command = "npm run build"
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Environment variables for build
  NODE_ENV = "production"
  VITE_API_BASE_URL = "https://your-backend-domain.com/api"
  VITE_SERVER_BASE_URL = "https://your-backend-domain.com"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://your-backend-domain.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration (if using Netlify Functions for backend)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Dev server configuration
[dev]
  command = "npm start"
  port = 5173
  publish = "dist"
