[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  VITE_API_BASE_URL = "/.netlify/functions"

[[redirects]]
  from = "/r/:shortId"
  to = "/.netlify/functions/redirect?id=:shortId"
  status = 302

[[redirects]]
  from = "/q/:shortId" 
  to = "/.netlify/functions/redirect?id=:shortId"
  status = 302

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self';"
